import { Question, FormTheme } from '@/types';

export interface FormTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  iconName: string;
  theme: FormTheme;
  welcome_title: string;
  welcome_description: string;
  welcome_button_text: string;
  thank_you_title: string;
  thank_you_description: string;
  questions: Omit<Question, 'form_id'>[];
}

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'customer_satisfaction',
    name: 'Customer Satisfaction Survey',
    category: 'Feedback',
    description: 'Collect ratings, net promoter score, and actionable customer feedback.',
    iconName: 'Smile',
    theme: {
      backgroundColor: '#191919',
      textColor: '#FFFFFF',
      buttonColor: '#0445AF',
      buttonTextColor: '#FFFFFF',
      questionTextColor: '#FFFFFF',
      answerTextColor: '#367EE9',
      fontFamily: 'Inter',
    },
    welcome_title: 'We value your opinion!',
    welcome_description: 'Help us improve our service by taking this 1-minute survey.',
    welcome_button_text: 'Start Survey',
    thank_you_title: 'Thank you for your feedback!',
    thank_you_description: 'Your responses directly shape our product roadmap.',
    questions: [
      {
        id: 'q_cs_1',
        type: 'rating',
        title: 'How would you rate your overall experience with our service?',
        description: '1 star = Poor, 5 stars = Excellent',
        required: true,
        order: 0,
        options: ['1', '2', '3', '4', '5'],
      },
      {
        id: 'q_cs_2',
        type: 'multiple_choice',
        title: 'Which aspect of our platform do you value the most?',
        description: 'Choose your top pick',
        required: true,
        order: 1,
        options: ['Form Builder Experience', 'Fast Page Load Speed', 'Analytics & Reporting', 'Custom Design Themes'],
      },
      {
        id: 'q_cs_3',
        type: 'yes_no',
        title: 'Would you recommend us to a friend or colleague?',
        description: '',
        required: true,
        order: 2,
      },
      {
        id: 'q_cs_4',
        type: 'long_text',
        title: 'What is one thing we could do to make your experience even better?',
        description: 'Optional comments or suggestions',
        required: false,
        order: 3,
      },
    ],
  },
  {
    id: 'lead_gen',
    name: 'Lead Generation & Contact',
    category: 'Sales',
    description: 'Capture high-intent leads with qualified contact questions.',
    iconName: 'Users',
    theme: {
      backgroundColor: '#0F172A',
      textColor: '#F8FAFC',
      buttonColor: '#6366F1',
      buttonTextColor: '#FFFFFF',
      questionTextColor: '#F8FAFC',
      answerTextColor: '#818CF8',
      fontFamily: 'Inter',
    },
    welcome_title: "Let's work together",
    welcome_description: 'Tell us a bit about your business and goals.',
    welcome_button_text: 'Get Started',
    thank_you_title: "We've received your request!",
    thank_you_description: 'Our team will review your inquiry and reach out within 24 hours.',
    questions: [
      {
        id: 'q_lg_1',
        type: 'short_text',
        title: 'What is your full name?',
        description: '',
        required: true,
        order: 0,
      },
      {
        id: 'q_lg_2',
        type: 'email',
        title: 'What is your business email address?',
        description: 'We promise no spam.',
        required: true,
        order: 1,
      },
      {
        id: 'q_lg_3',
        type: 'dropdown',
        title: 'What is your monthly project budget?',
        description: '',
        required: true,
        order: 2,
        options: ['$1,000 - $5,000', '$5,000 - $15,000', '$15,000 - $50,000', '$50,000+'],
      },
      {
        id: 'q_lg_4',
        type: 'long_text',
        title: 'Briefly describe your project requirements',
        description: '',
        required: true,
        order: 3,
      },
    ],
  },
  {
    id: 'event_rsvp',
    name: 'Event RSVP & Registration',
    category: 'Events',
    description: 'Register attendees for summits, workshops, or webinars.',
    iconName: 'Calendar',
    theme: {
      backgroundColor: '#111827',
      textColor: '#F9FAFB',
      buttonColor: '#10B981',
      buttonTextColor: '#FFFFFF',
      questionTextColor: '#F9FAFB',
      answerTextColor: '#34D399',
      fontFamily: 'Inter',
    },
    welcome_title: 'Typeform Tech Summit 2026',
    welcome_description: 'Reserve your spot for keynotes, workshops, and networking.',
    welcome_button_text: 'Register Now',
    thank_you_title: 'You are registered!',
    thank_you_description: 'We sent calendar invite details to your email.',
    questions: [
      {
        id: 'q_ev_1',
        type: 'short_text',
        title: 'Full Name for your summit badge',
        description: '',
        required: true,
        order: 0,
      },
      {
        id: 'q_ev_2',
        type: 'email',
        title: 'Email Address for confirmation',
        description: '',
        required: true,
        order: 1,
      },
      {
        id: 'q_ev_3',
        type: 'multiple_choice',
        title: 'Which track will you primarily attend?',
        description: '',
        required: true,
        order: 2,
        options: ['Frontend & UX Innovations', 'Backend Architecture & AI', 'Product & Design Thinking'],
      },
      {
        id: 'q_ev_4',
        type: 'yes_no',
        title: 'Will you join the networking dinner after keynotes?',
        description: 'Complimentary dinner provided.',
        required: true,
        order: 3,
      },
    ],
  },
  {
    id: 'product_feedback',
    name: 'Product Feedback & Feature Request',
    category: 'Product',
    description: 'Gather feature requests, bug reports, and user feedback.',
    iconName: 'Sparkles',
    theme: {
      backgroundColor: '#030712',
      textColor: '#F9FAFB',
      buttonColor: '#8B5CF6',
      buttonTextColor: '#FFFFFF',
      questionTextColor: '#F9FAFB',
      answerTextColor: '#A78BFA',
      fontFamily: 'Inter',
    },
    welcome_title: 'Help Us Build Better Features',
    welcome_description: 'We test new features based on direct user feedback.',
    welcome_button_text: 'Give Feedback',
    thank_you_title: 'Thanks for sharing your thoughts!',
    thank_you_description: 'Our product team reads every submission.',
    questions: [
      {
        id: 'q_pf_1',
        type: 'rating',
        title: 'How satisfied are you with our latest release?',
        description: '1 = Very Dissatisfied, 5 = Highly Satisfied',
        required: true,
        order: 0,
        options: ['1', '2', '3', '4', '5'],
      },
      {
        id: 'q_pf_2',
        type: 'multiple_choice',
        title: 'What type of feedback are you submitting today?',
        description: '',
        required: true,
        order: 1,
        options: ['Feature Request', 'Usability Improvement', 'Bug Report', 'General Praise'],
      },
      {
        id: 'q_pf_3',
        type: 'long_text',
        title: 'Please elaborate on your feedback or feature idea',
        description: 'Include any context or steps to reproduce if reporting an issue',
        required: true,
        order: 2,
      },
    ],
  },
  {
    id: 'job_application',
    name: 'Job Application & Candidate Intake',
    category: 'HR & Hiring',
    description: 'Streamline job candidate screening and portfolio collection.',
    iconName: 'Briefcase',
    theme: {
      backgroundColor: '#F8FAFC',
      textColor: '#0F172A',
      buttonColor: '#0284C7',
      buttonTextColor: '#FFFFFF',
      questionTextColor: '#0F172A',
      answerTextColor: '#0284C7',
      fontFamily: 'Inter',
    },
    welcome_title: 'Join Our Engineering Team',
    welcome_description: 'We are looking for passionate builders. Fill out this brief application.',
    welcome_button_text: 'Apply Now',
    thank_you_title: 'Application Received!',
    thank_you_description: 'Our recruiting team will review your application and respond within 3 business days.',
    questions: [
      {
        id: 'q_job_1',
        type: 'short_text',
        title: 'What is your full name?',
        description: '',
        required: true,
        order: 0,
      },
      {
        id: 'q_job_2',
        type: 'email',
        title: 'Primary Contact Email',
        description: '',
        required: true,
        order: 1,
      },
      {
        id: 'q_job_3',
        type: 'dropdown',
        title: 'How many years of experience do you have in fullstack software development?',
        description: '',
        required: true,
        order: 2,
        options: ['0 - 2 years', '3 - 5 years', '5 - 8 years', '8+ years'],
      },
      {
        id: 'q_job_4',
        type: 'short_text',
        title: 'Link to your GitHub profile or Portfolio URL',
        description: '',
        required: true,
        order: 3,
      },
    ],
  },
];
